### ISSUE TITLE
User Story - View All Wigs

### ISSUE THREAD

**Issue by DDVVPP** [thats-so-ravenclaw/grace-shopper#22]
As a user, I want to view all the wigs so that I can see what is available to purchase

- [x] React component - All Wigs #16 
- [x] React component - Wig thumbnail/info view #17 
- [x] Store #14 
- [x] API Routes: Wigs #9 
- [x] Models: Wigs #7 
- [x] Database creation #4 
- [x] Thunk Creator - Get all wigs #23
