### ISSUE TITLE
User Story - Add Items to Cart

### ISSUE THREAD

**Issue by nevette-bailey** [thats-so-ravenclaw/grace-shopper#42]
As a visitor, I want to add items to a cart for purchase, so that I can purchase them.

Subtasks:
- [x] cart view #20 
- [x] Redux store reflects cart #53
- [x] Update AllWigs component to implement Add to Cart functionality on button
- [x] Add cart to routes 
- [x] Add cart to Navbar so it's accessible 

If carts will be stored in db:
- [ ] api route to post order to database (unfulfilled) #52
- [ ] api route to put order to database (edit unfulfilled order) #52
- [ ] api route to delete order from database (unfulfilled order) #52
- [x] Sequelize model - orders #51
